### ISSUE TITLE
Missing `var`

### ISSUE THREAD

**Issue by krouskop** [peterhaldbaek/mt-latlon#1]
While using your library, I was getting this error under some circumstances:

<pre>
ReferenceError: l is not defined
    at /.../node_modules/mt-latlon/mt-latlon.js:408:13
    at String.replace (native)
    at Number.toPrecisionFixed (/.../node_modules/mt-latlon/mt-latlon.js:406:15)
</pre>

Adding a `var` to the start of line 408 in `mt-latlon.js` resolved the issue for me:

``` diff
@@ -403,11 +403,11 @@
         var n = this.toPrecision(precision);

         // ... but replace +ve exponential format with trailing zeros
         n = n.replace(/(.+)e\+(.+)/, function(n, sig, exp) {
           sig = sig.replace(/\./, '');       // remove decimal from significand
-          l = sig.length - 1;
+          var l = sig.length - 1;
           while (exp-- > l) sig = sig + '0'; // append zeros from exponent
           return sig;
         });

         // ... and replace -ve exponential format with leading zeros
```

**Comment by peterhaldbaek** [comment]
Good catch. I just pubilshed a new version (0.0.4) with the fix.
